sudo: false
language: ruby
cache: bundler
rvm:
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - "jruby-9.1.15.0"
  - "jruby-9.2.5.0"
  - "ruby-head"
  - "rubinius-3"
  - "jruby-head"
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius-3

before_install:
  - bundle --version || gem install bundler
  - gem update bundler
before_script:
  - cp test/functional/initializer.rb.ci test/functional/initializer.rb
script: bundle exec rake

env:
  global:
  - ADYEN_MERCHANT_ACCOUNT: "VanBergenORG"
  - ADYEN_API_USERNAME: "ws@Company.VanBergen"
  - ADYEN_API_PASSWORD: "7phtHzbfnzsp"

branches:
  only:
    - master
